google_maps:
  scraping_criteria:
    scrape_unscraped: true  # Whether to scrape establishments that haven't been scraped yet
    scrape_before_date: "2024-01-01"  # Only scrape establishments scraped before this date
    max_reviews_per_establishment: 1500  # Maximum number of reviews per establishment
    min_reviews_per_establishment: 100  # Minimum number of reviews per establishment
    max_total_reviews: 9500  # Maximum total reviews to scrape
    require_confirmation: true  # Whether to ask for confirmation before scraping
    custom_place_ids: ["ChIJ0c9vBG-2yhQRgLzf-6a4veg"]  # List of specific place IDs to scrape, overrides other criteria if not empty
  
  api_settings:
    translate: false  # Whether to translate reviews
    apify_token_file: "tokens/apify_token_dev2.txt"
    deepl_token_file: "tokens/deepl_token_dev.txt"
    deepseek_token_file: "tokens/deepseek_api_key.txt"
    translation_service: "deepseek"  # "deepl" or "deepseek"

    max_reviews: 1500
    reviews_sort: "newest"  # Sort order for reviews
    language: "en"  # Language for reviews
    reviews_origin: "all"  # Origin of reviews
    personal_data: false  # Whether to include personal data

trustpilot:
  scraping_criteria:
    scrape_unscraped: false  # Whether to scrape establishments that haven't been scraped yet
    scrape_before_date: "2024-04-07"  # Only scrape establishments scraped before this date
    max_establishments: 500
    custom_place_ids: ["ChIJW40wCG-2yhQRuPTD5f7bqIc"]

  api_settings:
    translate: false
    apify_token_file: "tokens/apify_token_dev2.txt"
    deepl_token_file: "tokens/deepl_token_dev.txt"
    deepseek_token_file: "tokens/deepseek_api_key.txt"
    translation_service: "deepseek"  # "deepl" or "deepseek"

    start_page: 1
    count: 500
    minDelay: 3000
    replies: false
    sort: "recency"
    startPage: 1
    verified: false

analysis:
  composite_score_weights:
    # Rating and volume (30%)
    avg_rating: 17.5  # Reduced from 20
    total_reviews: 7.5
    rating_consistency: 5
    
    # Sentiment removed from the composite score calculation
    # Using aspect based sentiment instead

    # Aspects sentiments (20%)
    service_sentiment: 7.5  # Reduced from 10
    quality_sentiment: 7.5  # Reduced from 10
    price_sentiment: 5
    # response_rate: 5  # Reduced from 5 to 0, while responding to each review is not necessary
    
    # Customer loyalty (5%)
    customer_loyalty_score: 5  # Reduced from 10
    
    # Temporal factors (15%)
    recent_reviews_pct: 10 
    rating_trend: 5
    
    # Authenticity and trustworthiness (15%)
    verified_reviewer_pct: 5
    authenticity_concerns: -5
    avg_cluster_similarity: -2.5
    similar_review_rate: -2.5

    # Communication and resolution (15%)
    complaint_rate: -5
    complaint_response_rate: 5
    resolution_language_rate: 5

  # Filtering settings
  filtering:
    min_reviews_threshold: 50  # Minimum number of reviews required for an establishment to be included in analysis